//===========================Filter===========================
export const FILTER_PIC = 'FILTER_PIC'
export const FILTER_DISTRICT = 'FILTER_DISTRICT'
export const FILTER_SCHOOL_YEAR = 'FILTER_SCHOOL_YEAR'
export const FILTER_SCHOOL_TYPE = 'FILTER_SCHOOL_TYPE'
export const FILTER_SCHOOL_LEVEL = 'FILTER_SCHOOL_LEVEL'
// export const FILTER_SCHOOL_SCALE = 'FILTER_SCHOOL_SCALE'
export const FILTER_SCHOOL_STATUS = 'FILTER_SCHOOL_STATUS'
export const FILTER_PURPOSE = 'FILTER_PURPOSE'
export const FILTER_ASSIGNED = 'FILTER_ASSIGNED'

export const FILTER_REPORT_RESULT = 'FILTER_REPORT_RESULT'
export const FILTER_DATE_RANGE = 'FILTER_DATE_RANGE'
// export const FILTER_FROM_DATE = 'FILTER_FROM_DATE'
// export const FILTER_TO_DATE = 'FILTER_TO_DATE'

export const FILTER_TASK_STATUS = 'FILTER_TASK_STATUS'

export const FILTER_ACTIVE = 'FILTER_ACTIVE'
export const FILTER_ROLE = 'FILTER_ROLE'

export const FILTER_SERVICE_STATUS = 'FILTER_SERVICE_STATUS'
export const FILTER_SERVICE_TYPE = 'FILTER_SERVICE_TYPE'
export const FILTER_EXPIRED = 'FILTER_EXPIRED'

export const FILTER_KPI_STATUS = 'FILTER_KPI_STATUS'


export const FILTER_DASHBOARD_SALE = 'FILTER_DASHBOARD_SALE'
export const FILTER_DASHBOARD_UNIT = 'FILTER_DASHBOARD_UNIT'
export const FILTER_DASHBOARD_SCHOOL_STATUS = 'FILTER_DASHBOARD_SCHOOL_STATUS'
export const FILTER_DASHBOARD_SCHOOL_LEVEL = 'FILTER_DASHBOARD_SCHOOL_LEVEL'
export const FILTER_DASHBOARD_SCHOOL_TYPE = 'FILTER_DASHBOARD_SCHOOL_TYPE'
export const FILTER_DASHBOARD_DISTRICT = 'FILTER_DASHBOARD_DISTRICT'

//===========================Search field===========================
export const ENTER_SEARCH_KEYWORD = 'ENTER_SEARCH_KEYWORD'

//===========================Sorting===========================
export const SORT_BY = 'SORT_BY'

//==========================Pagination==========================
export const CHANGE_PAGE = 'CHANGE_PAGE'