export const data = [
    {
        id: 1,
        schoolName: 'Trần Quang Khải',
        type: 'Công lập',
        district: '1',
        address: '68/29B Trần Quang Khải, P.Tân Định',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Tiểu học',
    },
    {
        id: 2,
        schoolName: 'Trần Khánh Dư',
        type: 'Công lập',
        district: '1',
        address: '105 Nguyễn Thái Bình, P.Nguyễn Thái Bình ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Tiểu học',
    },
    {
        id: 3,
        schoolName: 'Đuốc Sống',
        type: 'Bán công',
        district: '3',
        address: '44 Phó Đức Chính, P.Nguyễn Thái Bình ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Tiểu học',
    },
    {
        id: 4,
        schoolName: 'Đinh Tiên Hoàng',
        type: 'Công lập',
        district: '4',
        address: '2B Lương Hữu Khánh, P.Phạm Ngũ Lão ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Tiểu học',
    },
    {
        id: 5,
        schoolName: 'Nguyễn Bỉnh Khiêm',
        type: 'Công lập',
        district: '6',
        address: '93 - 95 A Lê Thị Riêng, P.Bến Thành ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Trung học cơ sở',
    },
    {
        id: 6,
        schoolName: 'Hòa Bình',
        type: 'Ngoài công lập',
        district: '5',
        address: '71 Trần Hưng Đạo, P.Cầu Ông Lãnh ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Trung học phổ thông',
    },
    {
        id: 7,
        schoolName: 'Đoàn Kết',
        type: 'Công lập',
        district: '7',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Trung học phổ thông',
    },
    {
        id: 8,
        schoolName: 'Lương Thế Vinh',
        type: 'Công lập',
        district: '3',
        address: '67 Đinh Tiên Hoàng, P.Đa Kao  ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Tiểu học',
    },
    {
        id: 9,
        schoolName: 'Khai Minh',
        type: 'Bán công',
        district: 'Bình Chánh',
        address: '181 Hoàng Sa, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Trung học phổ thông',
    },
    {
        id: 10,
        schoolName: 'Nguyễn Thái Bình',
        type: 'Công lập',
        district: 'Bình Tân',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Trung học cơ sở',
    },
    {
        id: 11,
        schoolName: 'Nguyễn Huệ',
        type: 'Công lập',
        district: '6',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Trung học phổ thông',
    },
    {
        id: 12,
        schoolName: 'Trần Quốc Tuấn',
        type: 'Công lập',
        district: '3',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Trung học phổ thông',
    },
    {
        id: 13,
        schoolName: 'Trần Quang Diệu',
        type: 'Công lập',
        district: '4',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Tiểu học',
    },
    {
        id: 14,
        schoolName: 'Nguyễn Thị Thập',
        type: 'Bán công',
        district: '5',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Trung học cơ sở',
    },
    {
        id: 15,
        schoolName: 'Nguyễn Hữu Thọ',
        type: 'Bán công',
        district: '1',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Trung học phổ thông',
    },
    {
        id: 16,
        schoolName: 'Lê Lợi',
        type: 'Ngoài công lập',
        district: '7',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Tiểu học',
    },
    {
        id: 17,
        schoolName: 'Lê Lai',
        type: 'Ngoài công lập',
        district: 'Nhà Bè',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Trung học phổ thông',
    },
    {
        id: 18,
        schoolName: 'Trưng Vương',
        type: 'Bán công',
        district: '1',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Trung học phổ thông',
    },
    {
        id: 19,
        schoolName: 'Tự Do',
        type: 'Công lập',
        district: '2',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Trung học cơ sở',
    },
    {
        id: 20,
        schoolName: 'Nguyễn Khuyến',
        type: 'Công lập',
        district: '4',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Trung học cơ sở',
    },
    {
        id: 21,
        schoolName: 'Hòa Hưng',
        type: 'Bán công',
        district: '7',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Trung học phổ thông',
    },
    {
        id: 22,
        schoolName: 'Hoàn Hảo',
        type: 'Công lập',
        district: 'Tân Bình',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Tiểu học',
    },
    {
        id: 23,
        schoolName: 'Khánh Hội',
        type: 'Ngoài công lập',
        district: '4',
        address: '68/29B Trần Quang Khải, P.Tân Định',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Tiểu học',
    },
    {
        id: 24,
        schoolName: 'Hoàng Diệu',
        type: 'Công lập',
        district: '1',
        address: '105 Nguyễn Thái Bình, P.Nguyễn Thái Bình ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Tiểu học',
    },
    {
        id: 25,
        schoolName: 'Hàn Thuyên',
        type: 'Công lập',
        district: '6',
        address: '93 - 95 A Lê Thị Riêng, P.Bến Thành ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Trung học cơ sở',
    },
    {
        id: 26,
        schoolName: 'Hải Hoàng',
        type: 'Ngoài công lập',
        district: '5',
        address: '71 Trần Hưng Đạo, P.Cầu Ông Lãnh ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Trung học phổ thông',
    },
    {
        id: 27,
        schoolName: 'Độc Lập',
        type: 'Công lập',
        district: '7',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Trung học phổ thông',
    },
    {
        id: 28,
        schoolName: 'Lương Tâm',
        type: 'Ngoài công lập',
        district: '3',
        address: '67 Đinh Tiên Hoàng, P.Đa Kao  ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Tiểu học',
    },
    {
        id: 29,
        schoolName: 'Cống Quỳnh',
        type: 'Công lập',
        district: '1',
        address: '181 Hoàng Sa, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Trung học phổ thông',
    },
    {
        id: 30,
        schoolName: 'Nguyễn Duy Trinh',
        type: 'Công lập',
        district: 'Bình Tân',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Trung học cơ sở',
    },
    {
        id: 31,
        schoolName: 'Trần Quốc Toản',
        type: 'Bán công',
        district: '1',
        address: '68/29B Trần Quang Khải, P.Tân Định',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Tiểu học',
    },
    {
        id: 32,
        schoolName: 'Trần Huy Liệu',
        type: 'Ngoài công lập',
        district: 'Tân Bình',
        address: '105 Nguyễn Thái Bình, P.Nguyễn Thái Bình ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Tiểu học',
    },
    {
        id: 33,
        schoolName: 'Nguyễn An Ninh',
        type: 'Công lập',
        district: '3',
        address: '44 Phó Đức Chính, P.Nguyễn Thái Bình ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Tiểu học',
    },
    {
        id: 34,
        schoolName: 'Đinh Lễ',
        type: 'Công lập',
        district: '4',
        address: '2B Lương Hữu Khánh, P.Phạm Ngũ Lão ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Tiểu học',
    },
    {
        id: 35,
        schoolName: 'Nguyễn Du',
        type: 'Ngoài công lập',
        district: '6',
        address: '93 - 95 A Lê Thị Riêng, P.Bến Thành ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Trung học cơ sở',
    },
    {
        id: 36,
        schoolName: 'Thái Bình',
        type: 'Bán công',
        district: '5',
        address: '71 Trần Hưng Đạo, P.Cầu Ông Lãnh ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Trung học phổ thông',
    },
    {
        id: 37,
        schoolName: 'Đoàn Dự',
        type: 'Công lập',
        district: '7',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Trung học phổ thông',
    },
    {
        id: 38,
        schoolName: 'Lương Văn Can',
        type: 'Ngoài công lập',
        district: '3',
        address: '67 Đinh Tiên Hoàng, P.Đa Kao  ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Tiểu học',
    },
    {
        id: 39,
        schoolName: 'Khai Tâm',
        type: 'Bán công',
        district: '1',
        address: '181 Hoàng Sa, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Trung học phổ thông',
    },
    {
        id: 40,
        schoolName: 'Nguyễn Trãi',
        type: 'Ngoài công lập',
        district: '2',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Trung học cơ sở',
    },
    {
        id: 41,
        schoolName: 'Trần Khắc Chung',
        type: 'Công lập',
        district: 'Bình Chánh',
        address: '68/29B Trần Quang Khải, P.Tân Định',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Tiểu học',
    },
    {
        id: 42,
        schoolName: 'Trần Khát Chân',
        type: 'Ngoài công lập',
        district: '1',
        address: '105 Nguyễn Thái Bình, P.Nguyễn Thái Bình ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Tiểu học',
    },
    {
        id: 43,
        schoolName: 'Hồng Hà',
        type: 'Bán công',
        district: '3',
        address: '44 Phó Đức Chính, P.Nguyễn Thái Bình ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Tiểu học',
    },
    {
        id: 44,
        schoolName: 'Đinh Bộ Lĩnh',
        type: 'Công lập',
        district: '4',
        address: '2B Lương Hữu Khánh, P.Phạm Ngũ Lão ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Tiểu học',
    },
    {
        id: 45,
        schoolName: 'Nguyễn Bính',
        type: 'Công lập',
        district: '6',
        address: '93 - 95 A Lê Thị Riêng, P.Bến Thành ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Trung học cơ sở',
    },
    {
        id: 46,
        schoolName: 'Sơn Bình',
        type: 'Ngoài công lập',
        district: '5',
        address: '71 Trần Hưng Đạo, P.Cầu Ông Lãnh ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Trung học phổ thông',
    },
    {
        id: 47,
        schoolName: 'Đoàn Thị Điểm',
        type: 'Công lập',
        district: '7',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Trung học phổ thông',
    },
    {
        id: 48,
        schoolName: 'Trương Vĩnh Ký',
        type: 'Ngoài công lập',
        district: '3',
        address: '67 Đinh Tiên Hoàng, P.Đa Kao  ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Tiểu học',
    },
    {
        id: 49,
        schoolName: 'Nguyễn Thị Minh Khai',
        type: 'Bán công',
        district: '1',
        address: '181 Hoàng Sa, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Trung học phổ thông',
    },
    {
        id: 50,
        schoolName: 'Nguyễn Thái Sơn',
        type: 'Ngoài công lập',
        district: '1',
        address: '68/29B Trần Quang Khải, P.Tân Định ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Trung học cơ sở',
    },
    {
        id: 51,
        schoolName: 'Hoàng Diệu',
        type: 'Bán công',
        district: '1',
        address: '68/29B Trần Quang Khải, P.Tân Định',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Tiểu học',
    },
    {
        id: 52,
        schoolName: 'Việt Anh',
        type: 'Ngoài công lập',
        district: '1',
        address: '105 Nguyễn Thái Bình, P.Nguyễn Thái Bình ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Cũ',
        level: 'Tiểu học',
    },
    {
        id: 53,
        schoolName: 'Đinh Thiện Lý',
        type: 'Ngoài công lập',
        district: '7',
        address: '80 Nguyễn Đức Cảnh, P. Tân Phong ',
        contact: '038484288',
        representor: 'Hồ Quang Tuấn',
        status: 'Mới',
        level: 'Trung học phổ thông',
    },
]
