export const PIC_FILTER = 'PIC'
export const DISTRICT_FILTER = 'district'
export const SCHOOL_YEAR_FILTER = 'schoolYear'
export const STATUS_FILTER = 'status'
export const PURPOSE_FILTER = 'purpose'
export const DATE_RANGE_FILTER = 'dateRange'
